## Node Export ------------------------------------------------------------------------
-
  name: 'Node Export'
  uriPattern: 'api/export-node/{identifier}'
  defaults:
    '@package': 'Sandstorm.E2ETestTools'
    '@controller': 'NodeExport'
    '@action': 'index'
    '@format': 'json'

-
  name: 'Site Export'
  uriPattern: 'api/export-node'
  defaults:
    '@package': 'Sandstorm.E2ETestTools'
    '@controller': 'NodeExport'
    '@action': 'index'
    '@format': 'json'




