## Node Export ------------------------------------------------------------------------
# api/export-node?node=<serialized NodeAddress> - used by the Export Node inspector button
-
  name: 'Node Export'
  uriPattern: 'api/export-node'
  defaults:
    '@package': 'Sandstorm.E2ETestTools'
    '@controller': 'NodeExport'
    '@action': 'index'
    '@format': 'yaml'
